[package]
name = "code-playground"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.0"
env_logger = "0.10.0"
log = "0.4.17"
serde = "1.0.152"
uuid = "1.2.2"
