# -----------------------------------------------------------------------------
# Codam Coding College, Amsterdam @ 2023.
# See README in the root project for more information.
# -----------------------------------------------------------------------------

# Configurations for the webserver
[network]
ip = "127.0.0.1"
port = 4242
timeout = 10
origins = ["https://codam.nl"]

# Configurations of the overall execution
[executor]
timeout = 5000

# Convention:
# {sourceFile} => The file with the source code.
# {targetFile} => The compiled binary file to execute.
# {flags} => The compile or intepreter flags.

[[executor.languages]]
name = "c"
extension = "c"
compile = "gcc {flags} {sourceFile} -o {targetFile}"
run = "{targetFile}"

[[executor.languages]]
name = "cpp"
extension = "cpp"
compile = "g++ {flags} {sourceFile} -o {targetFile}"
run = "./{targetFile}"

# Assuming we only support single source files.
[[executor.languages]]
name = "rust"
extension = "rs"
run = "cargo script {flags} {sourceFile}"